name: Main
on:
  push:
    branches: [main]
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: {node-version: '20.19', cache: 'npm', cache-dependency-path: 'package-lock.json'}
      - run: npm ci
      - run: npm run typecheck && npm run lint && npm run test && npm run build:production
      - uses: actions/upload-artifact@v4
        with: {name: kids-mua-frontend, path: dist/kids-mua-frontend}
